Added impedance mode for ANT neuro devices
brainflow-dev/brainflow pull request #751
Opened 2024-12-23 14:57 UTC by bdieudonne

2024-12-23 23:50 UTC, Andrey1994 commented
Hi, thanks, I will review tomorrow

2024-12-24 22:42 UTC, Andrey1994 reviewed
there is `get_resistance_channels` methods in brainflow api which is supposed to be used to mark impedance values.
ANT neuro devices have quite a lot of channels so I dont think that we should extend the whole package with 2 times more channels, but we can add resistance_channels into `brainflow_boards.cpp` and make them the same as exg channels. simplified example:

```
eeg_channels: {1,2,3,4...}
resistance_channels: {1,2,3,4...}
```

Then in user api it will be possible to write smth like:
```
resistance_channels = BoardShim.get_resistance_channels(board_id)
impedance_data = data[resistance_channels]
```

2024-12-24 22:42 UTC, Andrey1994 commented on docs/SupportedBoards.rst
> +    board = BoardShim(BoardIds.ANT_NEURO_EE_410_BOARD, params)  # 8 channel amplifier
that should not be here, its meant to be just a part to init the device
device specific code samples can be pushed into python_package/examples/tests
You can create an example with impedance checking and add a link for it to the docs

2025-01-03 15:29 UTC, bdieudonne commented
Thanks for reviewing! I pushed some updates based on your comments. Some remarks:

- The listing of eeg/emg/resistance/... channels manually feels a bit error prone. E.g., when you accidentally set the board to AntNeuroEE410 instead of AntNeuroEE411, I lost all my EEG data (because that one has no eeg_channels defined) -- while the ANT sdk itself could easily work device agnostic.
- I put the sampling counter at the end instead of at the beginning of the data package array (I saw the same is done for the gtec Unicorn), to avoid that corresponding channels would have different indices in EEG mode versus in impedance mode.
- I also removed sampling_rate from the brainflow_boards.cpp, as it is not fixed. Example to explain why:

```
params = BrainFlowInputParams()
board = BoardShim(BoardIds.ANT_NEURO_EE_410_BOARD, params)
board.prepare_session()
board.config_board('sampling_rate:500')
print(board.get_sampling_rate(board.board_id))
```
--> this would yield 2000, while I'd expect 2000

2025-01-05 19:02 UTC, Andrey1994 commented
>I also removed sampling_rate from the brainflow_boards.cpp, as it is not fixed. Example to explain why:

that should be restored, its known that sampling rate returned by BoardShim can be wrong if its manually overridden with config_board, it comes from the fact that its static info but there must be a default

2025-01-05 19:13 UTC, Andrey1994 requested changes

2025-01-05 19:13 UTC, Andrey1994 commented on python_package/examples/tests/eego_impedances_and_eeg.py
> +    for i in range(5):
dont see reasons for the loop here, just wait for 5 seconds and print will do the same

2025-01-05 19:13 UTC, Andrey1994 commented on python_package/examples/tests/eego_impedances_and_eeg.py
> +    for i in range(3):
the same here

2025-01-05 19:13 UTC, Andrey1994 commented on src/board_controller/ant_neuro/ant_neuro.cpp
> -        sampling_rate = board_descr["default"]["sampling_rate"];
need to restore, its used as a default

2025-01-05 19:13 UTC, Andrey1994 commented on src/board_controller/ant_neuro/ant_neuro.cpp
> +                std::this_thread::sleep_for (std::chrono::milliseconds (500));
is it correct? I dont rememeber how ant sdk works, but it looks like it might lead to the same speed of collecting data and slower speed of reading it from the buffer. So in the end it will result to overflow, lost packages and delay
Also, not sure why I've added sleep above, looks strange for me now also

2025-01-05 19:13 UTC, Andrey1994 commented on src/board_controller/brainflow_boards.cpp
> -        {"sampling_rate", 2000},
that should be restored

2025-01-05 19:13 UTC, Andrey1994 commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
package num is the first one for all boards and makes sense to keep it consistent

2025-01-06 09:44 UTC, bdieudonne commented on python_package/examples/tests/eego_impedances_and_eeg.py
> +    for i in range(5):
It's just a simple example that could be used as a starting point for some processing in blocks of 1 second, that easily generalizes to longer streams. The buffer should be emptied now and then to save memory, right? (Is there any guideline on how often the buffer should be emptied?)

2025-01-06 09:47 UTC, bdieudonne commented on src/board_controller/ant_neuro/ant_neuro.cpp
> +                std::this_thread::sleep_for (std::chrono::milliseconds (500));
From the ANT sdk manual: "Although it is called a stream, it is actually a state. Calling GetData() on an impedance stream returns the latest known impedance state." So there's no internal buffer for impedances

I guess the 1ms sleep is to give the hardware/cpu some rest (and/or allow other threads to do stuff)?

2025-01-06 10:10 UTC, bdieudonne commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
Note that ANT EEG streams have N+2 channels (N EEG + triggers + sample counter) and impedance streams have N+2 channels as well (M=N EEG + reference electrode + ground electrode). To have them both fit in the brainflow channels (now: N+2 + marker + time stamp), I saw four "reasonable" options:

1. Keep EEG stream as before --> EEG and impedance channels don't match, and there's no (room for) package num for impedances
    - EEG (as before):
        - chan 0: package num (= sample counter)
        - chan 1-N: EEG channels
        - chan N+1: triggers
        - chan N+2: time stamp channel
        - chan N+3: marker channel
    - impedances:
        - chan 0-N-1: EEG channels
        - chan N: reference channel 
        - chan N+1: ground channel
        - chan N+2: time stamp channel
        - chan N+3: marker channel
2. Set package num at N+1 for the EEG stream --> similar to gtec Unicorn integration, **agrees exactly with the default channel numbering of ANT SDK**, and **EEG and impedance channels match** (also no package num for impedances)
    - EEG:
        - chan 0-N-1: EEG channels
        - chan N: package num (= sample counter)
        - chan N+1: triggers
        - chan N+2: time stamp channel
        - chan N+3: marker channel
    - impedances:
        - chan 0-N-1: EEG channels
        - chan N: reference channel 
        - chan N+1: ground channel
        - chan N+2: time stamp channel
        - chan N+3: marker channel
3. Add an extra channel (N+5 channels) --> everything fits as well, but needs extra channel. Channels don't match exactly between EEG and impedances.
    - EEG:
        - chan 0: package num (= sample counter)
        - chan 1-N: EEG channels
        - chan N+1: triggers
        - chan N+2: empty
        - chan N+3: time stamp channel
        - chan N+4: marker channel
    - impedances:
        - chan 0: empty/manual package num
        - chan 1-N: EEG channels
        - chan N+1: reference channel 
        - chan N+2: ground channel
        - chan N+3: time stamp channel
        - chan N+4: marker channel
4. Add two extra channel (N+6 channels) --> everything fits as well, every channel has its own dedicated index, but needs 2 extra channels
    - EEG:
        - chan 0: package num (= sample counter)
        - chan 1-N: EEG channels
        - chan N+1: empty (~reference)
        - chan N+2: empty (~ground)
        - chan N+3: triggers
        - chan N+4: time stamp channel
        - chan N+5: marker channel
    - impedances:
        - chan 0: empty/manual package num
        - chan 1-N: EEG channels
        - chan N+1: reference channel 
        - chan N+2: ground channel
        - chan N+3: empty (~triggers)
        - chan N+4: time stamp channel
        - chan N+5: marker channel

I think option 1 is a no-go as it is confusing to have the EEG channels not match; I choose option 2 as it agrees best with ANT's sdk. Let me know what you think

2025-01-06 21:17 UTC, Andrey1994 commented on src/board_controller/ant_neuro/ant_neuro.cpp
> +                std::this_thread::sleep_for (std::chrono::milliseconds (500));
good, thanks!

2025-01-06 21:19 UTC, Andrey1994 commented on python_package/examples/tests/eego_impedances_and_eeg.py
> +    for i in range(5):
you can set the size of the buffer in start_stream method, there is a default also, its smth like 3600 * 250 and its a ring buffer

2025-01-06 21:36 UTC, Andrey1994 commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
I like option 4 with manual package num for impedance, its closer to what is implemented in other boards.

It also will be a breaking change since brainflow has playbackfileboard and read_file methods and all these 4 options will lead to the need to update recorded files. In option 4 it can be made with less harm, package number is at index 0 as before and eeg channels are at indexes 1-N as before, so for example this code will just work with older files:

```
data = DataFilter.read_file("old_ant.data")
eeg_channels = BoardShim.get_eeg_channels(board_id)
eeg_data = data[eeg_channels]
```

We technically can keep timestamps and markers working with old files if we put 

- chan N+1: reference channel
- chan N+2: ground channel
- chan N+3: empty (~triggers)

After timestamp and marker channels and dont change locations for timestamp and marker. But it will look a little bit strange, its common to put timestamps and markers in the end. So lets update it exactly like you propose in option 4

2025-01-06 21:37 UTC, Andrey1994 commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
- chan N+1: reference channel
- chan N+2: ground channel
- chan N+3: empty (~triggers)

And

- chan N+1: empty (~reference)
- chan N+2: empty (~ground)
- chan N+3: triggers

Should go to other_channels, right? Update in docs will be needed to reflect that

2025-01-09 16:19 UTC, bdieudonne commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
I don't know how other_channels is defined. Would you consider ground and reference as "other channels", if they are already listed in resistance_channels?

2025-01-09 16:50 UTC, bdieudonne commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
updated according to option 4 (hope i didnt make any typos)

2025-01-09 17:06 UTC, bdieudonne commented on src/board_controller/brainflow_boards.cpp
> +        {"package_num_channel", 9},
(it is still a breaking change, as the trigger channel, timestamp channel and marker channel have moved, as you noted)

2025-01-12 21:08 UTC, Andrey1994 approved these changes

2025-01-13 01:57 UTC, merged